### ISSUE TITLE
Make `nones_are_zeros` a keyword-only parameter in `FormulaEngine`

### ISSUE THREAD

**Issue by sahas-subramanian-frequenz** [frequenz-floss/frequenz-sdk-python#100]
Reading this, I recommend making the `nones_are_zeros` arguments a keyword-only argument (`def f(..., *, nones_are_zeros: bool`), otherwise is very hard to know what's going on on the caller site without having to go see the function definition.

_Originally posted by @leandro-lucarella-frequenz in https://github.com/frequenz-floss/frequenz-sdk-python/pull/95#discussion_r1038235546_

**Comment by leandro-lucarella-frequenz** [comment]
If this argument is only a temporary hack and will be removed in a future release, then I don't think this is worth it.

**Comment by llucax** [comment]
It seems like this argument didn't go away and it feels like it is not temporary anymore. We should decide what to do about it.
