### ISSUE TITLE
Handle `CancelledError` in all uses of `Task.exception()`

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#1026]
### What's needed?

`Task.exception()` returns caught exceptions as values, unless the caught exception is a `CancelledError`, in which case, it raises the `CancelledError` as well.

Our uses of `Task.exception()` might not be accounting for this behaviour and might need special handling if cancelling the parent task is not the right thing to do for any particular case.

**Comment by llucax** [comment]
I started working on this while we were talking about it.
