### ISSUE TITLE
Handle data from disk

### ISSUE THREAD

**Issue by matthias-wende-frequenz** [frequenz-floss/frequenz-sdk-python#132]
### What's needed?

We want an simple and efficient way to handle dumping and loading data from disk.

### Proposed solution

Add dumping the full buffer to disk and reload the buffer from disk to the [ring buffer](https://github.com/frequenz-floss/frequenz-sdk-python/pull/139).

The data should be stored when the application is terminated and on a regular basis, e.g. every 15 minutes.

### Open Questions

We are certainly creating gaps of missing data and it remains an open question how to handle this data. The simplest approach is to fill missing data with NaN, but other approaches like e.g. back filling are among the other options.

### Use cases

Let's consider an application that creates one feature from timeseries data. Usually we would think of creating a buffer, e.g. using a [ring buffer](https://github.com/frequenz-floss/frequenz-sdk-python/issues/113), that stores data for a certain time window, e.g. 15 minutes or 28 days.

When the application restarts, if there is no data on disk, it would take the time of the window size to rebuild this buffer and hence create this feature.

### Alternatives and workarounds

Instead of simply dumping the raw buffer to disk we could:

* Use the raw data and send it to the sdk's data pipeline,
* Write app that continuously stores data from the logical meter as files.

**Comment by mathias-baumann-frequenz** [comment]
A question in relation to this: Should we check for problems like full disk? I know from past experience that this this type of error can cause all kinds of strange behavior if not handled properly

**Comment by matthias-wende-frequenz** [comment]
I think that's a good idea :)

**Comment by mathias-baumann-frequenz** [comment]
Next question is then, should the class check that or something external to it
