### ISSUE TITLE
Implement BatteryPool

### ISSUE THREAD

**Issue by ela-kotulska-frequenz** [frequenz-floss/frequenz-sdk-python#140]
### What's needed?

User should be able to subscribe for data from some pool of Batteries.
BatteryPool should communicate with user using channels. This approach would be consisntent with LogicanMeter and EvChargerPool.

## What data are needed:
All these values will be packed in the class and send with one channel. We use DataSourceActor for IT!
* **total_capacity**: sum(battery.capacity for each working battery in battery pool)
* **max_capacity**: sum(battery.capacity * battery.max_soc for each working battery in battery pool)
* **min_capacity**:  sum(battery.capacity * battery.min_soc for each working battery in battery pool)
* **max_soc**: sum(battery.capacity*battery.max_soc for each working battery in battery pool)/total_capacity
* **min_soc**: sum(battery.capacity * battery.min_soc for each working battery in battery pool)/total_capacity 

All the value below will have their own channel.
* **average_soc**: sum(battery.capacity * battery.soc  for each working battery in battery pool)/total_capacity 
* **active_power** sum(battery.adjacent_inverter.active_power for each battery in the battery pool) - even if it is broken we need this information.

* TUPLE **power_supply_bound** : sum( min( battery.power_upper_bound, battery.adjacent_inverter.power_upper_bound ) for each working battery in battery pool )
* TUPLE **power_consumption_bound** : sum( max( battery.power_lower_bound, battery.adjacent_inverter.power_lower_bound ) for each working battery in battery pool )

### How frequently we should send data:
* Capacity, SoC bounds - when they change. These don't change frequently.
* SoP - This can change frequently. However it is not needed for any calculation. It is needed only before making charge/discharge decision.
    *  We could send new value only when it change. However this value are not needed frequently and we would compute it frequently. It seems to be lots of unnecessary work.
    *  User can ask for this value every-time when he needs it. But then we have no channel communication. It won't be possible to move BatteryPool to separate process. (**No** : Implementation should be consistent with Logical Meter. So we should use channels.)
* SoC - when it change
* active power - with given resampling frequency.

### Proposed solution

BatteryPool will use:
* BatteryPoolStatus - to know what batteries are working
* ComponentMetricResamplingActor - to subscribe for the metric data and receive them with some frequency. 
    *  Interpolation methods for the resampler:
          * Capacity, SoC bounds : Return last value -  This remains constant for most of the time, so returning last value seems to be correct.
          * SoP, SoC : 
               * Return last value  (forward filling) 
               * Linear interpolation. . Both SoC and SoP don't change the direction frequently. They either increases or decreases for some time. (or remain constant). If we find linear function based on first and last value in Resampler buffer, then we can predict the next value. How long time window we should store in ResamplerBuffer? After X seconds of inactivity battery/inverter will be considered as broken. (BatteryPoolStatus holds X argument). Time window could be X, too. Then we can interpolate as long as battery last message is considered as *relevant*.
          * active_power - average

### Open questions ###
* Different method to predict SoC, SoP.
* How frequently we should send SoP - it can change frequently. We could send it in second basis and user can use peekable feature to get the latest value.

**Comment by thomas-nicolai-frequenz** [comment]
> min/max of SoC bounds (maybe)

I think we should support this right away. Peak shaving I believe needs  to know the SoC bounds and so pretty much every application @idlir-shkurti-frequenz . It will have an impact on the **capacity** calculation we discussed in the slack channel today.

I would also suggest to provide the **min** and **max** SoP bounds. @tiyash-basu-frequenz The min bound will be a new upcoming feature by the Microgrid API that the `PowerManager` will need to support. Peak shaving shaving has already been tested with that feature by @idlir-shkurti-frequenz . @tiyash-basu-frequenz can shed more light onto that @ela-kotulska-frequenz Its quite an important feature we still need to test before the winter ends ;-) Its needed by the DC heating core app, however the SDK will have to support these min and max SoP bounds.

**Comment by thomas-nicolai-frequenz** [comment]
@ela-kotulska-frequenz when touching the BatteryPool I think we should start working / designing the PowerManager right away so that users would not directly need to be dealing with SoC and SoP bounds as well as talking care about the PowerDistributor. Of course up to you to decide. Just throwing that in as a point of discussion.

**Comment by thomas-nicolai-frequenz** [comment]
> Should active_power be returned from BatteryPool or LogicalMeter.

Depending on whether the metric changes if a battery fails is one way to decide. I would tend to say to place it in the BatteryPool for consistency and/or offer both options. If a user wants to include the ID of a battery in a LogicMeter formula there is nothing we can prevent the user of doing so. Thats why I'd say probably giving the a consistent option via the BatteryPool might not hurt even if it feels a bit redundant. However, key point is that the LogicalMeter does not know when a battery goes offline and the battery needs to be removed from the calculation. I think this logic should always stay inside the BatteryPool. Just my few thoughts about it .... This discussion will also come back with EvChargerPool or the InverterPool etc.

To me the biggest question is also if a user isn't confused when he gets almost all battery metrics from the Pool and suddenly the active power ends up in the LogicalMeter. Wouldn't that feel a bit strange? Usually there is a meter in front of each battery too that would equally return the active power. A battery can be take offline whereas a meter can't. Surely in both cases measurements would be zero.

**Comment by ela-kotulska-frequenz** [comment]
@thomas-nicolai-frequenz  
I discussed min/max bounds with Tiyash. I also need to add it to PowerDistributingActor.

I will focus on BatteryStatus first. The next important task would be to implement min bounds in PowerDistributingActor.
I will start PowerManager after that.

**Comment by thomas-nicolai-frequenz** [comment]
> I discussed min/max bounds with Tiyash. I also need to add it to PowerDistributingActor. I will focus on BatteryStatus first. The next important task would be to implement min bounds in PowerDistributingActor. I will start PowerManager after that.

Indeed, that makes a lot of sense. Thank you very much! I simply missed that, sorry for that. Good catch!

**Comment by idlir-shkurti-frequenz** [comment]
> MAYBE min/max SoC bounds out of all working batteries in the batter pool (maybe)

This is not something that peak shaving uses now or that we have any plans on using soon. I am not sure about other usecases but for now I can't think of any that use it. The mean SoC is the only one that is used by peak shaving at the moment.

**Comment by idlir-shkurti-frequenz** [comment]
> max_soc: sum(battery.capacity*battery.max_soc for each working battery in battery pool)/total_capacity

What exactly is the `battery.max_soc` in this formula?

**Comment by thomas-nicolai-frequenz** [comment]
> User should be able to subscribe for data from some pool of Batteries.

I struggled when I read the word "some" but it totally makes sense. A user might want to split up the entire pool of batteries in any given microgrid into two pools. That means a user should be able to:
1. Assign a list of battery ids to a pool
2. Provide no list and the pool will by default use all available batteries
