### ISSUE TITLE
PowerDistributingActor should use min SoP (inclusion/exclusion bounds)

### ISSUE THREAD

**Issue by ela-kotulska-frequenz** [frequenz-floss/frequenz-sdk-python#152]
### What's needed?

Microgrid will expose min bounds for charge/discharge power soon.
After that we should update PowerDistributing algorithm to look at it.

### Proposed solution

Implementation should be in old MOS repository, because in past we had this min bounds.
 To be checked

**Comment by leandro-lucarella-frequenz** [comment]
Blocking because we need a new version of the microgrid API service to be released for being able to merge this.

**Comment by thomas-nicolai-frequenz** [comment]
@shsms the min and max SoP bounds should be first exposed via the BatteryPool. Second step would also be to look at the bounds if someones sends a power request thats out of bounds.
