### ISSUE TITLE
ci: Check that `pip install frequenz-sdk` works in an arm64 environment

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#160]
### What's needed?

A CI check to ensure that we are able to install the sdk both in amd64 (which we already have) and arm64 environments.

This became a problem with `frequenz-sdk==0.16.0`, which installs fine in amd64 `python:3.11-slim` docker image,  but because of a dependency `grpcio==1.51.1`, requires a C++ compiler when installing in an arm64 image.

Having a test allows us to be aware of such issues and look for alternatives,  or at least provide documentation on how to deal with the issue.

**Comment by tiyash-basu-frequenz** [comment]
FYI, I am unable to reproduce the issue "requires a C++ compiler when installing in an arm64 image.".

As a simple installation test, I think building an image with the `--platform linux/arm64` flag and installing it there should be enough. We could go for build matrix here to test installation in multiple architectures.
