### ISSUE TITLE
Use Sample type in Ringbuffer

### ISSUE THREAD

**Issue by matthias-wende-frequenz** [frequenz-floss/frequenz-sdk-python#165]
### What's needed?

The `OrderedRingBuffer`s update method takes a timestamp and a value as parameters.
The default use case for this class is to store data coming from the logical meter, which sends data of type `Sample` which members are a timestamp and a value.

### Proposed solution

Move he ringbuffer to `timeseries` and use the `Sample` class.

### Alternatives and workarounds

Move the `Sample` class from the `timestamp` path to e.g. `util` and use it in the RingBuffer.

**Comment by shsms** [comment]
> Move the Sample class from the timestamp path to e.g. util and use it in the RingBuffer.

why do we have to move it?  you could just get it with: `from timeseries import Sample`

**Comment by matthias-wende-frequenz** [comment]
> why do we have to move it? you could just get it with: from timeseries import Sample

I think there is need to move it out any longer.

My concern was that when it's used outside of `timeseries` it becomes a more generic type and thus deserves it's place outside of `timeseries`.

But since we decided to move the ringbuffer to timeseries, this concern isn't valid any more.

Issue updated!
