### ISSUE TITLE
Remove timestamp normalization in OrderedRingBuffer

### ISSUE THREAD

**Issue by mathias-baumann-frequenz** [frequenz-floss/frequenz-sdk-python#183]
### What's needed?

We expect timestamps to come in exactly according to the sampling rate, no normalization is needed.

### Proposed solution

Remove the call to the normalization.

Open Question: Should we raise an exception if the timestamp is not aligned with the sampling rate?

**Comment by matthias-wende-frequenz** [comment]
Closing because having this feature seems useful. We can open again if we see any performance issues.
