### ISSUE TITLE
Benchmarks for the data sourcing actor

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#198]
### What's needed?

We need benchmarks for the data sourcing actor, where we see how long
it takes to stream a certain number of values for a certain number of
microgrid components.

### Proposed solution

Prereqs:
1. The `MockMicrogrid` package in tests currently [sends out 2000](https://github.com/frequenz-floss/frequenz-sdk-python/blob/2524cb2dddeeed00289e46aab4af8f0544ae9a33/tests/timeseries/mock_microgrid.py#L110)
   values per component_id.  This needs to be configurable.
   
2. The [`start`](https://github.com/frequenz-floss/frequenz-sdk-python/blob/0bcf61cb19ff52e7c64db14acdde11867c61f236/tests/timeseries/mock_microgrid.py#L89) method starts the data sourcing actor and the
   resampling actor, but sends out the channel only for the resampling
   actor.  There should ideally be a `start_mock_client` method that
   just sets up the mock client, which the `start` method calls.  Then
   we would be able just call `start_mock_client` and then create our
   own actor instances.

The data sourcing actor can be benchmarked by a function that takes as
input:
  - number of components
  - the number of messages to be sent out for each battery as inputs

This benchmarking function can be implemented like this:

1. Create a `MockMicrogrid` instance, with the given number of ev
   chargers like [here](https://github.com/frequenz-floss/frequenz-sdk-python/blob/2524cb2dddeeed00289e46aab4af8f0544ae9a33/tests/timeseries/test_logical_meter.py#L96-L99).
2. the `MockMicrogrid` has a default `sample_rate_s` of 0.01, this can
   be set to 0.0 (or almost 0.0 if there are synchronization issues).
3. Create a `DataSourcingActor` instance, and send requests to it for
   each of the [3 current phases](https://github.com/frequenz-floss/frequenz-sdk-python/blob/0bcf61cb19ff52e7c64db14acdde11867c61f236/src/frequenz/sdk/microgrid/component/_component.py#L126-L128),
   for all component ids in `MockMicrogrid.evc_ids`.  Collect the
   corresponding receivers into a `channels.MergeNamed` and count the
   number of messages received from each component_id+metrid_id pair.
4. Confirm the number of messages sent is the number of messages
   received.  Measure the time required to stream the configured
   number of messages.

**Comment by mathias-baumann-frequenz** [comment]
Should step 1. also add batteries and not just ev chargers?
