### ISSUE TITLE
Handle gaps in the `MovingWindow` data

### ISSUE THREAD

**Issue by matthias-wende-frequenz** [frequenz-floss/frequenz-sdk-python#213]
## Provide an interface for handling gaps

* the user should be able to tell what to do with gaps, e.g. replace with constant number, bfill ffill, interpolate
* should be able to get a list of all gaps

## Accessing behavior of uninitialized or missing data

We need to check if data is potentially uninitialized in the `__getitem__`
method and define what to do in that case.
The check can be performed by using the ringbuffers gaps. Thus we'd need to
check if the requested data subwindow intersects with any interval stored as gap.

### possible actions when uninitialized data is accessed:

* raise an exception
* return the biggest subset

**Comment by Marenz** [comment]
Gaps here refers to the gaps found in the OrderedRingBuffer class and how they can be handled

**Comment by matthias-wende-frequenz** [comment]
@cwasicki can we close this issue?

**Comment by cwasicki** [comment]
Do you remember who requested these features? 

>the user should be able to tell what to do with gaps, e.g. replace with constant number, 

This is available now.

> bfill ffill, interpolate

This is not supported but could be done by the user on the array.

> should be able to get a list of all gaps

This request was just closed: https://github.com/frequenz-floss/frequenz-sdk-python/issues/558

**Comment by matthias-wende-frequenz** [comment]
> Do you remember who requested these features?

I can't remember but might come from myself :). I'll close the issue now.
