### ISSUE TITLE
MovingWindow: Create Interface for requesting data and handling the data copy behaviour

### ISSUE THREAD

**Issue by matthias-wende-frequenz** [frequenz-floss/frequenz-sdk-python#214]
When asking the `MovingWindow` for a subwindow we might return a slice of the buffer, that means a reference to the underlying numpy based ringbuffer.
There are cases, e.g. when dealing with small window sizes and high sample rates, where the data might get updated from the data stream before the requested subwindow has been processed.

As a solution we want to tell the `MovingWindow` to return a copy of the data instead of a reference. In order to do that we need to add an interface, such that users can control copy behavior.

We might implement a method for the `MovingWindow` as follows.

```python
window(
	self,
	start: datetime,
	end: datetime,
	fill_gaps: Optional[Quantity] = None,
	force_copy: Bool = False
)
```

This method should return a sorted numpy array that holds the resampled data from start to end and fills the gaps with the Value that is provided by `fill_gaps`.

------------

Summary of the (ongoing) work related to this and what I see essential for v1.0.  

Essential for this issue:
* For v1.0:
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/641
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/598
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/638
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/668
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/672
  * https://github.com/frequenz-floss/frequenz-sdk-python/issues/676 (If not ready for v1.0 getitem magic should be removed before the release)
  
* Post v1.0?
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/669.
  * https://github.com/frequenz-floss/frequenz-sdk-python/issues/646

Related to moving window:
* For v1.0
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/664
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/670
* Post v1.0?
  * https://github.com/frequenz-floss/frequenz-sdk-python/issues/558

**Comment by matthias-wende-frequenz** [comment]
FYI @cwasicki @thomas-nicolai-frequenz

**Comment by thomas-nicolai-frequenz** [comment]
I don't understand why we could not design it in a way where the user passes his numpy array by reference the moving window is writing to. This way we could avoid the need for the fill_gaps parameter. In that case the numpy array could be initialised with whatever values the someone wants.

**Comment by cwasicki** [comment]
To me passing in an array feels less like typical behavior of other functions in numpy or pandas. 

> 	fill_gaps: Optional[Quantity] = None,

Since we should not have gaps in the moving window but only NaNs or uninitialized in the beginning, I would name this differently.

>start: datetime,
>end: datetime,

That should also work with index, not only datetime.

**Comment by matthias-wende-frequenz** [comment]
> I don't understand why we could not design it in a way where the user passes his numpy array by reference the moving window is writing to. This way we could avoid the need for the fill_gaps parameter. In that case the numpy array could be initialised with whatever values the someone wants.

This is about the gaps that are coming from the resampler, e.g. due to faulty hardware.

Passing the np array is also planned but an independent issue (https://github.com/frequenz-floss/frequenz-sdk-python/issues/530).

**Comment by thomas-nicolai-frequenz** [comment]
> This is about the gaps that are coming from the resampler, e.g. due to faulty hardware.

Yes but in this case we would copy the NaN's that are coming from the resampler. This has to be treated differently I think but not 100% sure.

**Comment by matthias-wende-frequenz** [comment]
> Yes but in this case we would copy the NaN's that are coming from the resampler. This has to be treated differently I think but not 100% sure.

You are right, we shouldn't copy NaN's. If `fill_gaps` is set to `None` and there are gaps then we should raise an exception.

**Comment by llucax** [comment]
Blocked because we need to fix some bugs in the ring buffer for this to be useful.

**Comment by cwasicki** [comment]
> Blocked because we need to fix some bugs in the ring buffer for this to be useful.

@llucax Which bugs are those?

**Comment by cwasicki** [comment]
> @llucax Which bugs are those?

Found it: https://github.com/frequenz-floss/frequenz-sdk-python/pull/578

**Comment by llucax** [comment]
OK, if you need any further info about this, ask @matthias-wende-frequenz

**Comment by thomas-nicolai-frequenz** [comment]
@leandro-lucarella-frequenz but this bug is fixed and merged. Can we unblock the issue?

**Comment by llucax** [comment]
Done.

**Comment by cwasicki** [comment]
@llucax As discussed summary of the (ongoing) work related to this and what I see essential for v1.0.  

Essential for this issue:
* For v1.0:
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/641
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/598
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/638
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/668
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/672
  * https://github.com/frequenz-floss/frequenz-sdk-python/issues/676 (If not ready for v1.0 getitem magic should be removed before the release)
  
* Post v1.0?
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/669.
  * https://github.com/frequenz-floss/frequenz-sdk-python/issues/646

Related to moving window:
* For v1.0
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/664
  * https://github.com/frequenz-floss/frequenz-sdk-python/pull/670
* Post v1.0?
  * https://github.com/frequenz-floss/frequenz-sdk-python/issues/558

**Comment by cwasicki** [comment]
Apart from a very special bug (#646) all associated work has been merged.
