### ISSUE TITLE
Create a util module in tests to share common test functionality

### ISSUE THREAD

**Issue by daniel-zullo-frequenz** [frequenz-floss/frequenz-sdk-python#223]
### What's needed?

The following function is duplicated in a couple of test modules

```python
@pytest.fixture
def fake_time() -> Iterator[time_machine.Coordinates]:
    """Replace real time with a time machine that doesn't automatically tick."""
    with time_machine.travel(0, tick=False) as traveller:
        yield traveller
```

### Proposed solution

Move that common/shared functionality into a new module so tests that needed can use it rather than duplicating it.

### Use cases

This is just to avoid code redundancy/duplication in tests.

**Comment by ela-kotulska-frequenz** [comment]
We have already util module in our tests directory :)
