### ISSUE TITLE
Documentation: Demonic Protection

### ISSUE THREAD

**Issue by ktickner** [frequenz-floss/frequenz-sdk-python#228]
We must provide users with the knowledge they need to use our systems whilst not exposing themselves to demonic entities.

> "To keep your grid free from any devils, the pentagram grid topology can be used as an exorcism for your local energy grid."

Further details may be required

**Comment by llucax** [comment]
I'm sorry, but I will close this one, it is too distracting as it keeps popping up when trying to plan work :shrug:
