### ISSUE TITLE
Create a BackgroundService class

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-sdk-python#240]
### What's needed?

Right now we have no common approach on how to manage classes/objects that spawn tasks. The most core example are actors, but we also have a lot of other classes that spawn tasks (like the resampler, moving window, etc.).

It should be possible to clearly control the lifespan of these objects, and be able to cleanly and clearly start and stop the tasks they spawn.

For now every class is doing their own thing, sometimes there is no way to stop things, sometimes there is but it is private, etc.

We should have a common way to do this.

### Proposed solution

Add a `BackgroundService` class to the SDK that provides a simple framework to handle this.

Here is a quick sketch of a possible implementation:

```py

class BackgroundService(ABC):

    def __init__(self):
        self.tasks: set[asyncio.Task] = set

    # async might not be really needed here, but allows sub-classes
    # to do async work as part of starting a task, which can be a
    # good thing since async initializaiton work can't be done in
    # __init__()
    @abstract
    async def start(self) -> None:
        pass

    @property
    def is_stopped(self) -> bool:
        for it in self.tasks:
            if t.done():
                return False
        return True
    def cancel(self) -> None:
        for t in self.tasks:
            t.cancel()

    async def join(self) -> None:
        await asyncio.gather(*[t.join() for t in self.tasks])

    async def stop(self) -> None:
        for t in self.tasks:
            await cancel_and_await(t)

    async __aenter__(self) -> None:
        await self.start()

    async def __aexit__(self, exc_type, exc, tb) -> None:
        await self.stop()

    def __del__(self) -> None:
        self.cancel()
        # Maybe see if there is a loop running and try to run await self.stop() in the loop?
```

(`join()` and `stop()` should probably be implemented using `asyncio.wait()` in a more resilient way)

Then all other classes can inherit from `BackgroundService`:

```py

class MovingWindow(BackgroundService):
    def __init__(self, other_params: ..., ...):
        super().__init__()

    async def start(self) -> None:
        self.tasks.add(asyncio.create_task(...))

mw = MovingWindow(...)
await mw.start()
...
await mw.stop()
```

### Use cases

* `Actor`
* `MovingWindow`
* `Resampler`
* etc.

### Additional context

# Advantages

* Having a common, well-known interface (consistency, ease of use, less cognitive burden for users to know what's going on)
* It allows full control over the lifespan of a worker
* It separates initialization from running the task, which could help avoid dependency problems if 2 *workers* need each other to run.
* It is explicit in terms of when something is running in the background or not.

# Disadvantages

* If people forget to call `start()` it might take a while to figure out what's going on.
* 

# Class name

I first thought of `Worker`, but it's not a great name, as it is usually used for something that runs in a thread and can run a task, but I could not think of a better name.

I thought of `Task` but it might be confusing given `asyncio.Task`, I thought of `BackgroundTask` as it is something that it is supposed to run in the background, opposed to a general `Task` that can also be some calculation for which you want some result, but want to run several calculations in parallel.

I thought of `Daemon` as the functionality is similar to a unix daemon. Or maybe `Service` in the same sense.  To make it more explicit I ended up with `BackgroundService`, as it will only be used to sub-class it shouldn't be too annoying to have a long name.

# References

* Coming originally from this PR discussion: https://github.com/frequenz-floss/frequenz-sdk-python/pull/190#discussion_r1100080476
* Discussed in: https://github.com/frequenz-floss/frequenz-sdk-python/discussions/197

**Comment by llucax** [comment]
For what is worth, the new `Selector` class was modeled after this idea, so it can be used as a starting point:

* https://github.com/frequenz-floss/frequenz-channels-python/pull/114
