### ISSUE TITLE
Add a `force` option in `PowerDistributingActor` `Request`

### ISSUE THREAD

**Issue by ela-kotulska-frequenz** [frequenz-floss/frequenz-sdk-python#259]
### What's needed?

As it was discussed, every component metric received from microgrid can be NaN. In that case metrics are independent from each: if one metric is NaN, then others can be correct float values.

PowerDistributingActor is ignoring components with NaN metrics, now.
But  when we do `gap_discharge` it should replace those metrics with the latest not-NaN values and use them.

### Proposed solution

1. Cache latest non-NaN value as use them if current metric is NaN and we do gap_discharge.
2. Create one more flag in the PowerDistributingActor request (*src/frequenz/sdk/actor/power_distributing/request.py*) : `gap_discharge`. Actor should set it to `True`, if he is doing `gap_discharge`. This should prevent from using cached values in the normal `set_power` operation. It should also simplify decision making process (less branches).

**Comment by leandro-lucarella-frequenz** [comment]
Shouldn't be whoever is doing the gap discharge responsible for doing this work (caching the last value, etc.)? Looks like out of the scope of the power distributing actor.

**Comment by leandro-lucarella-frequenz** [comment]
If what we need is a way to force the power distributor to apply some command to all batteries regardless of their working status, I would name that option just `force`. `gap_discharge` sounds too niche and only about one possible use case for this feature, but maybe I am mistaken.

**Comment by shsms** [comment]
I agree,  `gap_discharge` is a peak shaving concept.  Ideally it should not be mentioned anywhere in the sdk codebase or docs.
