### ISSUE TITLE
Retrieve and expose microgrid metadata

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-sdk-python#265]
### What's needed?

The microgrid API added a call to retrieve microgrid metadata. The metadata so far includes the microgrid ID and location (expressed in longitude and latitude). We need to expose that metadata in the SDK.

### Proposed solution

- [x] Expose the new `GetMetadata` gRPC call and its new associated types.
- [x] Retrieve the metadata when connecting to the microgrid in the `ConnectionManager`
- [x] Expose the ID and location, probably directly as a new attributes of the `ConnectionManager`: `sdk.microgrid.get().id` and `sdk.microgrid.get().location`
- [x] Calculate the timezone of a microgrid based on the location and expose it too. This can be easily done in python using the [`timezonefinder`](https://pypi.org/project/timezonefinder/) package.
- [x] #360

### Alternatives and workarounds

* Instead of exposing the attributes directly in the `ConnectionManager`, we could add a `sdk.microgrid.get().metadata` object and put the metadata there.
* We could not expose the timezone in the SDK and let users do the conversion themselves.

### Additional context

* https://github.com/frequenz-floss/frequenz-api-microgrid/pull/30
* https://github.com/frequenz-floss/frequenz-api-microgrid/blob/v0.x.x/proto/frequenz/api/microgrid/microgrid.proto

**Comment by llucax** [comment]
Blocked on #412
