### ISSUE TITLE
Application to write incoming data to a ringbuffer that gets dumped periodically

### ISSUE THREAD

**Issue by mathias-baumann-frequenz** [frequenz-floss/frequenz-sdk-python#267]
### What's needed?

To make historical data available for prediction, a new application should be written that:
* Gets its own repository
* Runs forever
* Should receive all desired metrics from the LogicalMeter and saves them into ringbuffers
* Dump those ringbuffers to disk periodically
* [optional] Also dump upon receiving a USR signal

Delete older files according to the following logic:
* Every Sunday 00:00 should be kept
* Keep the last N files and delete older files.

**Comment by matthias-wende-frequenz** [comment]
Btw you can use the MovingWindow to load data into a Ringbuffer.

**Comment by mathias-baumann-frequenz** [comment]
Moved to https://github.com/frequenz-io/RingbufferDumper/issues/1
