### ISSUE TITLE
Add a dispatch API client

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-sdk-python#290]
### What's needed?

We need to provide a dispatch API client.

### Proposed solution

Write a client based on what we have for the microgrid API.

This should live in `frequenz.sdk.dispatch.client` to also follow the microgrid API.

### Use cases

* Dispatch forwarding actor.
* Creation of dispatches by other actors.

### Alternatives and workarounds

Use the dispatch API directly.

### Additional context

Dispatching will be a core part of building actors and apps, so we need to include support for it in the SDK.

FYI @sahas-subramanian-frequenz @thomas-nicolai-frequenz

**Comment by leandro-lucarella-frequenz** [comment]
Blocked until we have the dispatch API open sourced.

**Comment by llucax** [comment]
This is done as a separate repo.
