### ISSUE TITLE
Grid protection checks in the PowerDistributor

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#296]
### What's needed?

The power distributor needs to make sure that any charge/discharge requests won't exceed the Grid/Fuse limit, before sending the requests to the Microgrid API.

For this to work,  the SDK needs to know the grid connection fuse limit,  which will be available from the microgrid API once this is implemented: https://github.com/frequenz-floss/frequenz-api-microgrid/issues/19

### Additional context

* https://github.com/frequenz-floss/frequenz-api-microgrid/issues/19
* #322 
* #360

**Comment by llucax** [comment]
@shsms didn't we say this one should be closed because it is at the wrong level?

**Comment by matthias-wende-frequenz** [comment]
Closing. Supposed to be covered by an (instantaneous) peak shaving aka grid protection actor.
