### ISSUE TITLE
Add a `linear_extrapolate` resampling function

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#307]
### What's needed?

Currently we have just an `average` function that we use for producing resampled data streams.  

We need to add an `linear_extrapolate` method.

### Use cases

This is required in grid safety usecases,  where we are need to detect grid breaches as soon as/about to happen instead of waiting for the average value to catch up.

**Comment by matthias-wende-frequenz** [comment]
Nice to have but we found out that it's not needed short term. We can reopen when it comes back to the table.
