### ISSUE TITLE
Document the terminology used around consumption and production

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-sdk-python#319]
### What's needed?

We need to document the terminology used to talk about production and consumption (of power, current, etc.).

The final proposal was posted in this discussion:
* https://github.com/frequenz-floss/frequenz-sdk-python/discussions/318?converting=1#discussioncomment-5589177	

### Proposed solution

Move the documentation to the Wiki, to its own page or the [Glossary](https://github.com/frequenz-floss/frequenz-sdk-python/wiki/Glossary) if that's a good fit.

### Alternatives and workarounds

The individual definitions should be also included in the code documentation, in the logical meter, battery pool, etc.

We could also include a summary of this terminology in the `frequenz.sdk.microgrid` module documentation.

**Comment by cwasicki** [comment]
Added a dedicated section to the glossary https://github.com/frequenz-floss/frequenz-sdk-python/wiki/Glossary#microgrid-power-terminology

**Comment by leandro-lucarella-frequenz** [comment]
Great, thanks! Closing. Feel free to reopen there was anything else to be done.
