### ISSUE TITLE
Resampler should align timestamps to Unix Epoch

### ISSUE THREAD

**Issue by sahas-subramanian-frequenz** [frequenz-floss/frequenz-sdk-python#328]
### What's needed?

Currently if the resampling actor is started with period 2sec, at 10:10:01.2,  then the messages out of the resampling actor would have timestamps:
 - 10:10:03.2
 - 10:10:05.2
 - 10:10:07.2

This means that if the resampling actor restarts,  timestamps will go out of sync.  They should instead be:
 - 10:10:02
 - 10:10:04
 - 10:10:06

### Proposed solution

The resampling actor should align timestamps to unix epoch, and not to actor start time, so that timestamps between restarts will still be compatible.

### Use cases

This is necessary 
- when dumping/loading data from the ring buffer.
- for usecases such as the 24hr forecast or peak shaving where we need the features to be aligned to unix epoch, specifically for 15min windows, i.e. 11:00, 11:15, 11:30, 11:45, 12:00, ... (copied from @idlir-shkurti-frequenz's comment below)

**Comment by idlir-shkurti-frequenz** [comment]
### Use cases:

This is necessary for usecases such as the 24hr forecast or peak shaving where we need the features to be aligned to unix epoch, specifically for 15min windows, i.e. 11:00, 11:15, 11:30, 11:45, 12:00, ...

**Comment by leandro-lucarella-frequenz** [comment]
I would make the alignment a new `ResamplerConfig` value, defaulting to the epoch.
