### ISSUE TITLE
Interface for fetching grid metrics: `frequency`

### ISSUE THREAD

**Issue by sahas-subramanian-frequenz** [frequenz-floss/frequenz-sdk-python#341]
### What's needed?

A high level interface for fetching grid frequency.

### Proposed solution

This can be done in two steps:

1. A method `microgrid.grid.frequency()` that takes an optional `component_id` of a meter,  from which it would stream frequency values. This value does not need to be resampled (so no need to get it from the resampler actor).  If no `component_id` is specified, use the meter closest to the grid, in the component graph.  If there are multiple meters close to the grid,  pick any one that has no successors.
2. Once the microgrid API starts supporting metadata for components,  a query interface around the component graph,  to identify meters with the best resolution, and get their component IDs,  which can be used in the methods from step 1, instead of having to specify component IDs in config files.

**Comment by matthias-wende-frequenz** [comment]
I looked into the FCR specs again and it looks that we don't need very fast reaction times and thus for now it's good enough if we address 1) by just using any meter.

**Comment by leandro-lucarella-frequenz** [comment]
@matthias-wende-frequenz will talk to Tom to decide whether to resample or not.

**Comment by matthias-wende-frequenz** [comment]
> @matthias-wende-frequenz will talk to Tom to decide whether to resample or not.

The verdict is that resampling is not needed.

**Comment by leandro-lucarella-frequenz** [comment]
Cool, updating the issue description (and hiding these comments as resolved to avoid the noise).

**Comment by david-natingga-frequenz** [comment]
> I looked into the FCR specs again and it looks that we don't need very fast reaction times and thus for now it's good enough if we address 1) by just using any meter.

1 sample per second or faster is sufficient. Anything slower puts an additional strain in the system. Although we could react possibly slower than once a second, we want to have some legroom and not make everything supertight.
