### ISSUE TITLE
Add a weather API client

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-sdk-python#352]
### What's needed?

We need to provide a weather API client.

### Proposed solution

Write a client based on what we have for the microgrid API.

This should live in `frequenz.sdk.weather.client` to also follow the microgrid API.

### Additional context

Dispatching will be a core part of building actors and apps, so we need to include support for it in the SDK.

FYI @sahas-subramanian-frequenz @thomas-nicolai-frequenz

**Comment by cwasicki** [comment]
@llucax Is this essential if we want to use weather forecasts in our forecasting actor?

**Comment by llucax** [comment]
This is being done as a separate repo.
