### ISSUE TITLE
BMS temperature data support

### ISSUE THREAD

**Issue by idlir-shkurti-frequenz** [frequenz-floss/frequenz-sdk-python#37]
### What's needed?

Battery temperature data is needed for lynch in order to decide whether to (dis)charge early within a 15min window.  Lynch will use the **max** temperature of all batteries in the microgrid. Hence only one value(highest temperature out of all batteries) is necessary for this usecase.

### Proposed solution

Either one value outputted which gives the max temperature or temperature of each battery. Both solutions work for this usecase.

### Use cases

Peak shaving (GMM)

### Additional context

Even though for peak shaving only the max temperature is required, usecases in the future might need separate temperatures for each battery.

**Comment by ela-kotulska-frequenz** [comment]
Hi @idlir-shkurti-frequenz 
Battery data has 3 kinds of temperature. Which one you need?
"temperature": {
    "avg": 24,
    "min": 22,
    "max": 26,
...
    },

**Comment by idlir-shkurti-frequenz** [comment]
If `max` is the maximum temperature of all batteries at the current time then I need `max`.

**Comment by ela-kotulska-frequenz** [comment]
No no xD

Protobuf BatteryData message has 3 values:
raw.battery.data.temperature.max
raw.battery.data.temperature.min
raw.battery.data.temperature.avg

Which one you need? Definitions in the API:
https://github.com/frequenz-floss/frequenz-api-microgrid/blob/v0.x.x/proto/frequenz/api/microgrid/battery.proto#L178-L180
https://github.com/frequenz-floss/frequenz-api-microgrid/blob/v0.x.x/proto/frequenz/api/microgrid/common.proto#L48-L56

**Comment by idlir-shkurti-frequenz** [comment]
Ah ok I see. For this usecase we need the `max` value.

**Comment by sahas-subramanian-frequenz** [comment]
@ela-kotulska-frequenz ~the max/min from protobuf are for individual blocks.  We need to expose only the `avg`,  because that's the temperature of each bms.~

EDIT: after speaking with Ela,  it sounds like we need the max.
