### ISSUE TITLE
Use the new microgrid API release v0.15.1

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-sdk-python#412]
### What's needed?

We need to make the SDK use the microgrid v0.14.0 as the microgrid service will be soon upgraded to this version.

### Proposed solution

Bump the dependency and fix the code.

### Additional context

* After this other new features present in v0.14.0 will need to be implemented, so more issues about this might come in the near future.

**Comment by llucax** [comment]
@tiyash-basu-frequenz This is ready to be merged as soon as the microgrid service is also upgraded. We should sync about this.
