### ISSUE TITLE
Set timestamps from microgrid to components data cache

### ISSUE THREAD

**Issue by daniel-zullo-frequenz** [frequenz-floss/frequenz-sdk-python#414]
### What's needed?

Repeated calls to `time.monotonic_ns` when creating the cache entries in https://github.com/frequenz-floss/frequenz-sdk-python/blob/v0.x.x/src/frequenz/sdk/actor/power_distributing/power_distributing.py#L82 might cause performance issues as  `time.monotonic_ns` is currently called for each incoming battery message.

### Proposed solution

Use timestamps coming from the microgrid component data + TTL to set the expiry time instead.

**Comment by daniel-zullo-frequenz** [comment]
I think this will be no longer needed once https://github.com/frequenz-floss/frequenz-sdk-python/issues/665 is addressed. @sahas-subramanian-frequenz can you please check and close this ticket if that's the case?

**Comment by shsms** [comment]
oh right, this can be closed.
