### ISSUE TITLE
Remove obsolete uses of `typing.*`

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#433]
Oh, interesting that you can use `type` as a *generic type*, maybe you should replace the other `Type` uses?

_Originally posted by @leandro-lucarella-frequenz in https://github.com/frequenz-floss/frequenz-sdk-python/pull/422#discussion_r1219819082_

**Comment by llucax** [comment]
I want to eventually add [`pyupgrade`](https://github.com/asottile/pyupgrade) to `repo-config`, which should do this automatically: https://github.com/asottile/pyupgrade#pep-585-typing-rewrites

I guess this is a motivation to do it sooner than later, will probably be more worth investing the time in integrating `pyupgrade` than in fixing it manually :)
