### ISSUE TITLE
Producer production power

### ISSUE THREAD

**Issue by matthias-wende-frequenz** [frequenz-floss/frequenz-sdk-python#446]
### What's needed?

The positive (and clipped) version of the producer power.

That'd be needed since the producer power is negative due to the negative sign convention and we are having similar functions for the consumer power.

**Comment by llucax** [comment]
@matthias-wende-frequenz Was this fixed by https://github.com/frequenz-floss/frequenz-sdk-python/pull/444?

**Comment by shsms** [comment]
> @matthias-wende-frequenz Was this fixed by https://github.com/frequenz-floss/frequenz-sdk-python/pull/444?

I'm not @matthias-wende-frequenz , but #444 added only the passive sign convention method which will always stream negative values.  This issue is about providing a positive value stream.

**Comment by llucax** [comment]
Thank you non-@matthias-wende-frequenz !

**Comment by llucax** [comment]
@matthias-wende-frequenz will talk to Tom and Christoph to see if this is necessary.

**Comment by matthias-wende-frequenz** [comment]
Issue can be closed.

References for further context:

https://github.com/frequenz-floss/frequenz-sdk-python/pull/746
https://github.com/frequenz-floss/frequenz-sdk-python/pull/697
