### ISSUE TITLE
Disable default constructor for derived `Quantity` types

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#452]
Allow only the `from_` methods for constructing these objects.

From @llucax:

Yup, it should be possible to use `__new__` to construct the object.

It can also be done in a follow-up PR also, I wouldn't block this PR on this.

I think we did that with some other class. Ah, yeah, the `AsyncConstructible`:

* https://github.com/frequenz-floss/frequenz-sdk-python/blob/650d0586c73d8cda4f1f496540ace4484abebe79/src/frequenz/sdk/_internal/_asyncio.py#L36-L48
* https://github.com/frequenz-floss/frequenz-sdk-python/blob/650d0586c73d8cda4f1f496540ace4484abebe79/src/frequenz/sdk/timeseries/battery_pool/_component_metric_fetcher.py#L38-L63

_Originally posted by @llucax in https://github.com/frequenz-floss/frequenz-sdk-python/pull/422#discussion_r1234195497_

**Comment by llucax** [comment]
Assigned to 0.22.0 because it will be a breaking change otherwise (if people start using the normal constructor). But I don't think it should be a release blocker.
