### ISSUE TITLE
Basic microgrid concepts and component graph

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-sdk-python#456]
### What's needed

We need to introduce new users to the basic concepts of a microgrid.

## Proposed solution

Add a document in `docs/` that is part of the navigation bar called something like `Microgrid 101` which includes:

* Briefly explains what a microgrid is
* Which type of components a microgrid can have
* How could they be connected among each other
* Shows a components graph example
* Maybe map them to the SDK API documents so users can do the mental map between concepts and SDK code entities.

**Comment by shsms** [comment]
@thomas-nicolai-frequenz we are trying to write documentation for the SDK  developer site,  and were thinking of writing a "Microgrid 101" page,  with details mentioned above,  but I was also wondering what level of detail to go into.

If these are being covered elsewhere already,  we can just write some basic details from the POV of the sdk and point users to the other page if they want details.

If the SDK is going to be the starting point for the docs,  then I can document them in more detail.

**Comment by thomas-nicolai-frequenz** [comment]
> I was also wondering what level of detail to go into

I suggest to keep this very brief for now. Surely its important to explain the concept of a component graph and that requires to understand what a microgrid is. I guess a simple mermaid example chart may be a good way but I would really keep it very, very short for now. We can always come back an extend it later on.
