### ISSUE TITLE
`BatteryPool` should expose a temperature receiver

### ISSUE THREAD

**Issue by christianparpart** [frequenz-floss/frequenz-sdk-python#466]
### What's needed?

By migrating away from `PowerDistributor` and use of `BatteryData` / `InverterData`, the only thing missing is access to the `temperature` of a battery(-pool).

### Proposed solution

`BatteryPool.temperature` should stream objects that contain the min/max/avg block temperatures of all batteries in the pool.  The returned objects could implement `__iter__`, so they can be directly used in a loop.  But it is nice to use an class, rather than a list, because later on we can add more methods for finding the hottest block, avg of all batteries, etc.

The fields could probably be called {temp_lowest/temp_highest/temp_avg} to indicate they are not bounds, but actual measurements.

This can be implemented with the same approach as `soc` and `capacity`.

### Use cases

Analogous to `soc`, `power`, `power_bounds`, `capacity`, add a `temperature` receiver.

### Alternatives and workarounds

still depend on `BatteryData` and legacy APIs :)

### Additional context

This is my second attempt to migrate our PQ actor to the BatteryPool :)

**Comment by thomas-nicolai-frequenz** [comment]
> BatteryPool.temperature should stream objects that contain the min/max/avg block temperatures of all batteries 
 
 We need to revise this. The battery pool should expose:
 
 1. Average temperature of the entire battery pool
 2. The highest and lowest temperature in a given pool on a per battery level (NOT block level)
 
 > min/max/avg block temperatures
 
The block concept is not a common concept and thus the smallest unit we should look at is on a per battery level. Also keep in mind that the temperature might not be available for batteries that are liquid cooled like the Tesla Megapack. We need to account for that in the documentation.

**Comment by thomas-nicolai-frequenz** [comment]
@sahas-subramanian-frequenz I need to revise the above. In this issue we should only expose the average temperature across all batteries in a given pool. That means averaging the average temperature reported by each battery. The metric for each battery is being exposed in the `MetricAggregation` message.

```Protobuf
message MetricAggregation {
  // The average value of the metric.
  float avg = 1;

  ...
}
```

If there are any further requirements lets address them in a new issue please @christianparpart

**Comment by llucax** [comment]
Is really average temperature useful at all? If you have 9 batteries ar 20 degrees and 1 at 70, shouldn't users know that one battery is really hot instead of thinking that all are at 25 degrees? My impression is that providing an average could make users have a false sense of security and very prone to miss important issues.

**Comment by thomas-nicolai-frequenz** [comment]
> If you have 9 batteries ar 20 degrees and 1 at 70, shouldn't users know that one battery is really hot instead of thinking that all are at 25 degrees?

It depends on the use case. The max is the least helpful figure of all. If one out of ten batteries is very hot it means the available SoP is reduced by just 10%. I am not sure what one would do with the information of the max temperature to be honest. Whats important is to know the average across all batteries. The max doesn't even help to know the distribution and or how many batteries are in a critical state. There is only one use case right now that requires the average temperature.

**Comment by shsms** [comment]
> My impression is that providing an average could make users have a false sense of security and very prone to miss important issues.

this is also why using SoP as an indicator of temperature (or other) issues would give clearer indications to users.  SoP of the pool is not average, but the sum.  So if the SoP of one battery starts to drop,  it will be noticeable.  Further SoP drops exponentially, with linear temperature increase:  https://github.com/frequenz-io/nitrogen-core-apps/blob/v0.x.x/docs/images/bounded-exp-decay.png

**Comment by thomas-nicolai-frequenz** [comment]
> this is also why using SoP as an indicator of temperature

@sahas-subramanian-frequenz agreed but it really depends on the specific use case.
