### ISSUE TITLE
Set timezone globally

### ISSUE THREAD

**Issue by ela-kotulska-frequenz** [frequenz-floss/frequenz-sdk-python#49]
### What's needed?

Timezone is hardcoded now in many places in the code. We use: `datetime.now(tz=pytz.UTC)` everywhere.

### Proposed solution

We should set timezone once globally at the start of the program.
https://stackoverflow.com/questions/1301493/setting-timezone-in-python

### Use cases

Otherwise module that forgot timezone would work wrong.

### Alternatives and workarounds

Have one global config variable for the timezone.

**Comment by leandro-lucarella-frequenz** [comment]
We should always use datetime objects that are timezone aware, so this is not needed if we do that.
