### ISSUE TITLE
Improve `BatteryPool` docs about streaming soc and capacity independent of inverter status

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#543]

**Comment by shsms** [comment]
I just remembered when writing the issue, that this is behaving as designed.  So I decided to write this note instead: 

BatteryPool is expected to report only the usable SoC and Capacity of the pool.  And if a corresponding inverter is out of order,  then that capacity and SoC are not usable,  so the values from such batteries should not be considered.

I will keep this issue open until the next SDK meeting, just in case.

**Comment by thomas-nicolai-frequenz** [comment]
I think this should be clearly document in case this isn't yet. 

> And if a corresponding inverter is out of order, then that capacity and SoC are not usable

That totally makes sense imho

**Comment by llucax** [comment]
This wasn't mentioned in the last meeting, maybe you want to add it to the agenda @shsms ?
