### ISSUE TITLE
Add timestamp in Power Distributing Result

### ISSUE THREAD

**Issue by david-natingga-frequenz** [frequenz-floss/frequenz-sdk-python#551]
### What's needed?

Add timesetamp in Power Distributing Result:
- We need to know when exactly the power was set.

### Use cases

FCR Balancing actor

### Alternatives and workarounds

Just get the time when the Result arrives, which is a very imperfect way to do this.

**Comment by matthias-wende-frequenz** [comment]
> We need to know when exactly the power was set.

I don't think we can do that, since we don't get this information from the hardware. 
The best you can do is subscribe to the return channel and use the timestamp of the returned message.

**Comment by Marenz** [comment]
After some talking and with the new SDK changes which uses proposals instead of power requests, a good way to get what is needed here (probably?) is to use the `battery_pool.power()`  method..

**Comment by llucax** [comment]
OK, closing as invalid.
