### ISSUE TITLE
Use `start_delay` when creating the resampler `Timer`

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-sdk-python#556]
### What's needed?

We needed to introduce a hack to make the timer start delayed so it can be synced with the resampler alignment. We need to remove that hack eventually.

### Proposed solution

Update to a new `channels` version that supports adding a start delay to the timer.

### Additional context

Fixes a hack introduced in:

* https://github.com/frequenz-floss/frequenz-sdk-python/pull/520

**Comment by matthias-wende-frequenz** [comment]
@llucax is this done?

**Comment by llucax** [comment]
Nope, it might even need a new channels release first. Super low prio though, it is just code cleanup.

**Comment by matthias-wende-frequenz** [comment]
Can we move it to post 1.0 then?

**Comment by llucax** [comment]
I would leave it here for now, when upgrading to channels 1.0.0 it is probably trivial to change this as part of the upgrade.

**Comment by matthias-wende-frequenz** [comment]
I'm not sure if that works. The reason is that we can set a start_delay but we can't set the now when initializing the timer and thus we can't guaranty that the timer is accurately aligned.

**Comment by llucax** [comment]
What do you mean by *set the now*?

**Comment by llucax** [comment]
This will be resolved with #802.
