### ISSUE TITLE
Add a `LogicalMeter` implementation

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#61]
### What's needed?

A `LogicalMeter` implementation will have to support the follow (method) streams:

1. Grid meter power measurement
2. **Client load (sink/black hole - unknown consumer&producer)** DEPRECATED!
3. Battery meter power measurement
4. PV meter power measurement
5. EV meter power measurement
6. CHP meter power measurement
....

Their default formulas will be inferred from the component graph,  and the formulas can be overridden from the UI.

It should connect to the `ResamplingActor` to get resampled data for individual components.

### Tasks

- [x] #66 
    - [x] Formula engine that can apply simple formulas on `Sample` streams.
    - [x] Parsing of manual formulas specified in the UI
- [x] #102
- [x] #133 

cc: @leandro-lucarella-frequenz @tiyash-basu-frequenz @ela-kotulska-frequenz

**Comment by thomas-nicolai-frequenz** [comment]
> client load

We will need a clear definition for the client load aka sink or black hole ;-) @sahas-subramanian-frequenz and I discussed this and we did not have a good solution. It essentially means the product or consumption excluding EV, battery, pv power and everything else we can measure. Its the `remaining power` (sink/blackbox) and it computes by subtracting everything thats measurable from the overall grid power. However, this will not always hold true. In some cases we might have a dedicated meter for the sink(s). In this case a meter has no child components. That means we may end up with two types of layouts:

1. Grid side meter plus meter for each microgrid component type e.g. battery, ev charger etc.
2. No grid side meter but one or multiple meter that don't have a child component, thus considered a sink (black hole) plus a meter for each microgrid component

Thus the client load computation is highly topology dependent whereas the other measurement methods aren't. The second problem is that each user might have different ideas what considers client load and what isn't.

Finally, we may not be able to provide the client load stream at all and fail with an exception if the user hasn't provided a manual formula in the UI. The graph might be incompletely configured etc. 

What use case does need the client load?

**Comment by shsms** [comment]
After an offline discussion with @thomas-nicolai-frequenz , we decided to make not expose a "client load" formula from the `LogicalMeter`, and instead provide two approaches for users to manipulate the formulas in specific ways:

1. a way to combine (add/subtract) the outputs of formulas, to create higher-order formulas
2. a way to exclude components of a specific type from a formula.

and apps can calculate client load this way,  by excluding batteries from the grid power, for example.

**Comment by thomas-nicolai-frequenz** [comment]
> apps can calculate client load this way, by excluding batteries from the grid power

@idlir-shkurti-frequenz any objections?

**Comment by thomas-nicolai-frequenz** [comment]
> a way to exclude components of a specific type from a formula.

... either by giving the ID of a component or excluding an entire component types like batteries, ev charger, ....

**Comment by idlir-shkurti-frequenz** [comment]
LGTM!

**Comment by shsms** [comment]
I was discussing with @tiyash-basu-frequenz about how to identify PV meters,  in order to automatically generate a formula for PV production.

The strategy is to check if a meter has a PV inverter as a successor. This works if the component graph has a PV inverter component,  but there might not always be a PV inverter component.  

There are locations where PV meters are dangling, without any PV inverter as successor,  especially if the PV inverter at the location doesn't have a communication interface.  Users would be able to add dummy PV inverters,  but they might not do it.  And in these locations,  we can't automatically generate a formula for PV power,  but users will have to provide a formula on the UI.

This also means that when apps want to calculate client load,  they will not be able to exclude PV by component type,  but will have to exclude the PV meter by component ID.

**Comment by thomas-nicolai-frequenz** [comment]
> There are locations where PV meters are dangling, without any PV inverter as successor, especially if the PV inverter at the location doesn't have a communication interface. Users would be able to add dummy PV inverters, but they might not do it.

If the user doesn't do that its not the job of the LogicalMeter to fix it. If there is no PV inverter then this is not consider a PV meter! Please keep things simple! Nothing the LogicalMeter/ComponentGraph should fix!

**Comment by thomas-nicolai-frequenz** [comment]
> but users will have to provide a formula on the UI.

That would be the alternative, sure.

**Comment by thomas-nicolai-frequenz** [comment]
> This also means that when apps want to calculate client load, they will not be able to exclude PV by component type, but will have to exclude the PV meter by component ID.

There is no such thing as client load!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! :-)

**Comment by shsms** [comment]
> There is no such thing as client load!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! :-)

yes, according to the SDK,  but @idlir-shkurti-frequenz would still have to know that this is the strategy,  because we also have locations where there are meters measuring PV power,  but without a PV inverter component in the graph.

**Comment by thomas-nicolai-frequenz** [comment]
> but @idlir-shkurti-frequenz would still have to know that this is the strategy, because we also have locations where there are meters measuring PV power, but without a PV inverter component in the graph.

then we should fix this by (order in priority):
1. Adding the PV inverter to the UI.
2. If 1 does not work which it should but just in case:
    - set custom formula for PV power computation in the UI using the component id's from the meter(s)
    - use `net_power = logical_meter.grid_power() - logical_meter.pv_power()`
    
Would that do it?

**Comment by shsms** [comment]
> Adding the PV inverter to the UI.

@tiyash-basu-frequenz this should be possible for our locations right?

**Comment by thomas-nicolai-frequenz** [comment]
> net_power = logical_meter.grid_power() - logical_meter.pv_power()

And this should be our default way to compute the net_power aka client load ;-) If we do this we have two ways of fixing the problem in no time, in both ways through the UI ;-) @idlir-shkurti-frequenz shout if this doesn't work!

**Comment by shsms** [comment]
> > net_power = logical_meter.grid_power() - logical_meter.pv_power()
>
> And this should be our default way to compute the net_power aka client load ;-)

yes,  that would be a very cool interface,  considering that that would be applying the `-` operation on two streams,  and produces a new stream that returns the calculated value.  It should be easy to achieve.  

I have turned the issue into a tracking issue,  with a number of sub-tasks listed (at the top of this page), to track all the desired features.

**Comment by matthias-wende-frequenz** [comment]
> There are locations where PV meters are dangling, without any PV inverter as successor, especially if the PV inverter at the location doesn't have a communication interface. Users would be able to add dummy PV inverters, but they might not do it. And in these locations, we can't automatically generate a formula for PV power, but users will have to provide a formula on the UI.

A grid that has dangling meters, except for the sink, would be rendered incomplete. I suggest to have the possibility to always have the possibility to add PV Inverters, even if they either don't have a communication interface or it's not used!

In the future having dangling meters could be a sanity check, i.e. if there is a meter node without any successor the micro-grid is not fully configured.

**Comment by thomas-nicolai-frequenz** [comment]
> In the future having dangling meters could be a sanity check, i.e. if there is a meter node without any successor the micro-grid is not fully configured.

There are plenty of meters that do not have a successors and don't need one. The current approach we have is pretty simple:

1. By default a developer can provide a custom formula for any method exposed in the LogicalMeter to override the automatic ComponentGraph computation
2. If no custom formula is provided the ComponentGraph is used to aggregates the time series

If neither 1 or 2 works the LogicalMeter will fail and throw an exception.

**Comment by sahas-subramanian-frequenz** [comment]
A basic implementation of the logical meter is now complete.  A few additional formulas and support for 3-phase current formulas need to be added,  but those are being tracked in other issues.
