### ISSUE TITLE
Define consumer and distinguish assets and devices in glossary

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-sdk-python#650]
### What's needed?

The glossary is not distinguishing devices and assets in the component section. Follow up on https://github.com/frequenz-floss/frequenz-sdk-python/pull/647#discussion_r1318691630

Also the term `consumer` should be defined in the glossary (see https://github.com/frequenz-floss/frequenz-sdk-python/wiki/Glossary#microgrid-power-terminology)

### Additional context

Also remove the word often from Time Series entry: `A sequence of [samples](#sample), often organized by [timestamp](#timestamp)`

**Comment by llucax** [comment]
What do you suggest is having different section for each type of those types or to have a definition for **Asset**? A more concrete proposal would be helpful.

**Comment by cwasicki** [comment]
Assigned it to myself and create a proposal PR after your one is merged.

**Comment by llucax** [comment]
@cwasicki is this done?

**Comment by cwasicki** [comment]
Started drafting it here: https://github.com/cwasicki/frequenz-sdk-python/pull/1. Will create a PR for this to upstream and ping again.

**Comment by cwasicki** [comment]
https://github.com/frequenz-floss/frequenz-sdk-python/pull/952
