### ISSUE TITLE
Restructure timeseries module

### ISSUE THREAD

**Issue by matthias-wende-frequenz** [frequenz-floss/frequenz-sdk-python#704]
### What's needed?

Some of the parts should move out of the module because they are not solely related to timeseries.

#### Quantities

* the quantity types

#### Data pipeline

* logical meter
* grid frequency

#### pools

* battery pool
* ...

### Alternatives and workarounds

Leave it as is.

### Additional context

https://github.com/frequenz-floss/frequenz-sdk-python/issues/84
https://github.com/frequenz-floss/frequenz-sdk-python/issues/575
https://github.com/frequenz-floss/frequenz-sdk-python/issues/222

**Comment by llucax** [comment]
Yeah, imho everything that is working with the micrograms should be in the microgrid namespace.

Also I would move actors to their domain namespace, and leave `actor` for the actor framework stuff. This is also a source of a lot of cyclic imports.

**Comment by llucax** [comment]
Closing in favor of #575.
