### ISSUE TITLE
Proposal life-time management in PowerManager's Matryoshka algorithm

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#727]
### What's needed?

We need a cleanup mechanism for old proposals under these situations:
  - when a new proposal for an existing priority+source_id is received with `None` values for both preferred power and bounds,
  - when the lifetime of a `BatteryPool` instance ends,

**Comment by matthias-wende-frequenz** [comment]
> when the lifetime of a BatteryPool instance ends,

when the channel gets closed

**Comment by shsms** [comment]
This is a bit urgent, because if one of the actors setting bounds goes away, its last preference would remain for ever.

I'm working on adding a timeout for every request sent to the PowerManager,  and that would transparently take care of this, because users are already having to repeat their commands, because after an gap they get dropped by the microgrid API otherwise.

Done here: https://github.com/frequenz-floss/frequenz-sdk-python/pull/845
