### ISSUE TITLE
Move `logical_meter.grid_power` to `microgrid.grid.power`

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-sdk-python#729]
Now that we have a `microgrid.grid` object, we should publish metrics there, like we do with `battery_pool`.

_Originally posted by @llucax in https://github.com/frequenz-floss/frequenz-sdk-python/pull/722#discussion_r1357871453_

Extra tasks:

- [ ] Update of the documentation including the code snippets on frequenz.com frontpage.

**Comment by matthias-wende-frequenz** [comment]
When changing, this needs also updating of the documentation including the code snippets on frequenz.com frontpage.

**Comment by daniel-zullo-frequenz** [comment]
This depends on the code changes done in #673 due to initialization so I'll base the code on the related PR #707

**Comment by christianparpart** [comment]
> we should publish metrics there, like we do with battery_pool.

@daniel-zullo-frequenz can you go a little bit more in detail on this, such that I could potentially take that ticket over? :-)

EDIT: never mind, just noticed you are already working on this.
