### ISSUE TITLE
Introduce a delay between actor restarts

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#732]
### What's needed?

Currently if an actor raises an exception, it is restarted immediately, but there should be a delay (of maybe 2 seconds) before the next restart is attempted.

Need to decide if this should be configurable.

**Comment by ktickner** [comment]
@llucax I am going to have a look at this one - but I am unable to assign myself. Are you able to assign me?

**Comment by christianparpart** [comment]
@ktickner damn, i just wanted to pick it, but then I read you. Did you start already?
