### ISSUE TITLE
Implement and expose voltage metrics

### ISSUE THREAD

**Issue by daniel-zullo-frequenz** [frequenz-floss/frequenz-sdk-python#783]
### What's needed?

Voltage metrics. These metrics are essential as they cover a wide range of use cases in electrical systems

### Proposed solution

The following metrics need to be implemented:
- Phase-to-phase voltage metric
- Phase-to-neutral voltage metric

### Use cases

- Fault Detection: monitoring phase-to-neutral voltage might help in identifying faults or irregularities in the electrical system
- Three-Phase systems: phase-to-phase voltage is essential for assessing the voltage between different phases 
which might help in load balancing across different phases, ensuring uniform distribution and preventing overload conditions

**Comment by matthias-wende-frequenz** [comment]
We can use two different Sample3Phase receivers here. One that returns the phase-to-neutral voltages and the other that sends the phase-to-phase voltages.
