### ISSUE TITLE
Update actor documentation

### ISSUE THREAD

**Issue by daniel-zullo-frequenz** [frequenz-floss/frequenz-sdk-python#797]
### What happened?

Initially, the actor was designed to run continuously unless there was an error or it was intentionally stopped. Later, the actor was updated to support a new use-case where the actor exits the running loop upon a normal termination.

The current actor documentation and examples primarily focus on stopping the actor manually, with only a brief mention that the actor also naturally terminates upon completing execution without errors. Some examples are either outdated or not entirely accurate.

For example, here it documents how it is expected to be used, as continuously running actors:  https://github.com/frequenz-floss/frequenz-sdk-python/blob/v1.x.x/src/frequenz/sdk/actor/__init__.py#L214-L218
In this part, it states that actors will be restarted only when it exits with errors: https://github.com/frequenz-floss/frequenz-sdk-python/blob/v1.x.x/src/frequenz/sdk/actor/__init__.py#L38-L40
And here actors are awaited to finish execution https://github.com/frequenz-floss/frequenz-sdk-python/blob/v1.x.x/src/frequenz/sdk/actor/__init__.py#L46-L48 but the examples only point out that actors needs to be manually stopped

For this example, the actor will block either until execution termination or until it gets stopped
https://github.com/frequenz-floss/frequenz-sdk-python/blob/v1.x.x/src/frequenz/sdk/actor/__init__.py#L70-L88

Also internal documentation needs to be updated to reflect what the code actually does.
For instance, the actor will also exit if it finishes execution successfully without any error but this is not reflected in the function documentation
https://github.com/frequenz-floss/frequenz-sdk-python/blob/v1.x.x/src/frequenz/sdk/actor/_actor.py#L75-L111

### What did you expect instead?

Update or extend documentation and examples in actor class and module to reflect what the actor code does, including the scenario where the actor terminates execution normally.

### Affected part(s)

Actors or actors utilities (decorator, etc.) (part:actor), Documentation (part:docs)

### Extra information

Related to https://github.com/frequenz-floss/frequenz-sdk-python/issues/632

**Comment by shsms** [comment]
It is also becoming more relevant now, as we are considering use cases where actor instances get spun up, run for a specific amount of time like a few hours, then exit.  Such uses should already be possible, but we can incorporate any insights gained from that experience into our actor documentation as well.

**Comment by llucax** [comment]
https://github.com/frequenz-floss/frequenz-sdk-python/blob/471adc6623507eeb2f9fba693a62b735365b6261/src/frequenz/sdk/actor/__init__.py#L214-L218

This doesn't look incorrect IMHO, it explicitly says one  can stop the actor manually. Do you mean we should just not mentioning that actors "normally should run forever", or that they could also stop on their own?

**Comment by llucax** [comment]
https://github.com/frequenz-floss/frequenz-sdk-python/blob/471adc6623507eeb2f9fba693a62b735365b6261/src/frequenz/sdk/actor/__init__.py#L38-L40

This also doesn't say unhanded errors are the **only** way an actor can be restarted, it says it is **automatically** restarted on errors.

**Comment by llucax** [comment]
https://github.com/frequenz-floss/frequenz-sdk-python/blob/471adc6623507eeb2f9fba693a62b735365b6261/src/frequenz/sdk/actor/__init__.py#L46-L48

Same here, this is only describing one feature, actors are async context managers and can be used like that, but you don't have to.

**Comment by llucax** [comment]
https://github.com/frequenz-floss/frequenz-sdk-python/blob/471adc6623507eeb2f9fba693a62b735365b6261/src/frequenz/sdk/actor/_actor.py#L75-L83

Yeah, this one should be definitely updated/fixed.

**Comment by shsms** [comment]
>  Do you mean we should just not mentioning that actors "normally should run forever", or that they could also stop on their own?

I think we should definitely mention "run forever" as a pattern, but it is starting to become just _one_ usage pattern, because we are now exploring other patterns, like actors managing and stopping sub-actors, etc.

I think we need to make changes only once we know what those other patterns look like and there is atleast one implementation that we've refined and like, and want to share.

**Comment by llucax** [comment]
So, in conclusion, after looking at the examples provided in the issue, I think the current docs are mostly correct, but I agree we could mention the case where an actor stops on its own (by just returning from the `run()` method normally) and add some example for that too.

**Comment by llucax** [comment]
> I think we need to make changes only once we know what those other patterns look like and there is atleast one implementation that we've refined and like, and want to share.

This also looks like a reasonable path to me, I would spend a lot of time documenting patterns that we didn't use that much and maybe they don't work out that well after all. I mean, we could make it more explicit that there are other ways to use actors but maybe not spend a lot of time adding examples of other specific pattern just now.

**Comment by llucax** [comment]
So I wonder if the priority high is really correct. Also @daniel-zullo-frequenz I think it would be helpful if you could submit a PR, even if it is a very rough draft, and maybe not even changing the text proper but just adding comments like "Here I would clarify X and Y" to have a better idea of how docs could look more clear to you.

**Comment by daniel-zullo-frequenz** [comment]
> This doesn't look incorrect IMHO, it explicitly says one can stop the actor manually. Do you mean we should just not mentioning that actors "normally should run forever", or that they could also stop on their own?

They could also terminate on their own without calling stop(), that's missing

**Comment by daniel-zullo-frequenz** [comment]
> So I wonder if the priority high is really correct. Also @daniel-zullo-frequenz I think it would be helpful if you could submit a PR, even if it is a very rough draft, and maybe not even changing the text proper but just adding comments like "Here I would clarify X and Y" to have a better idea of how docs could look more clear to you.

We can lower the priority if you think is not too bad. I initially spotted the internal documentation was outdated and also understood that just a few people are aware an actor can terminate execution normally without explicitly calling `stop()`. For instance, this comment in the example is not entirely correct as stated in the issue description [v1.x.x/src/frequenz/sdk/actor/__init__.py#L70-L88](https://github.com/frequenz-floss/frequenz-sdk-python/blob/v1.x.x/src/frequenz/sdk/actor/__init__.py?rgh-link-date=2023-11-28T11%3A28%3A19Z#L70-L88)

I can fix these small issues in the docs. And I agree to wait for the new patterns to be implemented/consolidated to write the docs about them if needed

**Comment by llucax** [comment]
Yeah, I definitely think we should fix anything that is wrong, and keep the wording open to imply other patterns are possible, and wait until mentioning explicitly how to use other patterns. Besides the places where you saw something was clearly wrong, I think the current docs are already open, they don't say, for example, that using `stop()` is the **only** way to stop an actor, it says you can call `stop()` to stop it. But feel free to include wording improvements in the PR if you think it is not open enough, again I think it will be much easier to discuss the subtleties in a PR, with an actual proposal, rather than in the issue.
