### ISSUE TITLE
Rename the "type" attribute of components in the component graph to "category"

### ISSUE THREAD

**Issue by jack-herrmann** [frequenz-floss/frequenz-sdk-python#992]
### What's needed?

This change would make the naming more consistent. The attribute "type" is also of type "ComponentCategory".

**Comment by llucax** [comment]
Why was this closed?

**Comment by jack-herrmann** [comment]
While there does an exist one called type, there also exists one called category. While both are of type ComponentCategory, I assumed this was intentional and there was a separate use for “type”.

**Comment by llucax** [comment]
Yes, correct, the type is used for something else.Inverters have a type for example.
